FROM python:3.11-slim
WORKDIR /app
COPY pyproject.toml poetry.lock* README.md ./
RUN pip install poetry && poetry config virtualenvs.create false && poetry install --no-root --without dev
COPY . .
CMD ["celery", "-A", "jobs.celery_app", "worker", "--loglevel=info"]
