// AUTO-GENERATED by hybrid-model/backend/scripts/export_metrics.py.
// DO NOT EDIT BY HAND. Run `poetry run python scripts/export_metrics.py`
// (from hybrid-model/backend) to regenerate from results/.
// Every number here is traceable to the source_file named in its section.

export const THESIS_METRICS = {
  "_meta": {
    "generated_by": "scripts/export_metrics.py",
    "dataset_version": "v2",
    "note": "AUTO-GENERATED. Do not edit by hand. Every number is traceable to the source_file named in its section."
  },
  "clean_eval": {
    "source_file": "results/clean_eval_results.csv",
    "rows": [
      {
        "model": "Baseline",
        "k": 5,
        "precision": 0.0132841328,
        "recall": 0.0094521919,
        "ndcg": 0.0115235318,
        "coverage": 0.01,
        "diversity": 0.9,
        "n_users_evaluated": 271
      },
      {
        "model": "Baseline",
        "k": 10,
        "precision": 0.0140221402,
        "recall": 0.0227437794,
        "ndcg": 0.0165610347,
        "coverage": 0.02,
        "diversity": 0.8888888889,
        "n_users_evaluated": 271
      },
      {
        "model": "Baseline",
        "k": 20,
        "precision": 0.0151291513,
        "recall": 0.0452910251,
        "ndcg": 0.0272629872,
        "coverage": 0.04,
        "diversity": 0.8789473684,
        "n_users_evaluated": 271
      },
      {
        "model": "Hybrid",
        "k": 5,
        "precision": 0.0095940959,
        "recall": 0.0082190257,
        "ndcg": 0.0099398619,
        "coverage": 0.526,
        "diversity": 0.6538745387,
        "n_users_evaluated": 271
      },
      {
        "model": "Hybrid",
        "k": 10,
        "precision": 0.0118081181,
        "recall": 0.0177281001,
        "ndcg": 0.0138917159,
        "coverage": 0.724,
        "diversity": 0.6964329643,
        "n_users_evaluated": 271
      },
      {
        "model": "Hybrid",
        "k": 20,
        "precision": 0.0123616236,
        "recall": 0.0352719236,
        "ndcg": 0.0219310502,
        "coverage": 0.872,
        "diversity": 0.7203728879,
        "n_users_evaluated": 271
      }
    ]
  },
  "components_eval": {
    "source_file": "results/components_eval.csv",
    "rows": [
      {
        "model": "Baseline",
        "k": 5,
        "precision": 0.0132841328,
        "recall": 0.0094521919,
        "ndcg": 0.0115235318,
        "coverage": 0.01,
        "diversity": 0.9,
        "n_users_evaluated": 271
      },
      {
        "model": "Popularity",
        "k": 5,
        "precision": 0.0125461255,
        "recall": 0.0100714988,
        "ndcg": 0.0145386923,
        "coverage": 0.01,
        "diversity": 0.9,
        "n_users_evaluated": 271
      },
      {
        "model": "ContentBased",
        "k": 5,
        "precision": 0.0162361624,
        "recall": 0.0097479806,
        "ndcg": 0.0150159347,
        "coverage": 0.722,
        "diversity": 0.0,
        "n_users_evaluated": 271
      },
      {
        "model": "Collaborative",
        "k": 5,
        "precision": 0.0177121771,
        "recall": 0.0134053523,
        "ndcg": 0.0165676632,
        "coverage": 0.428,
        "diversity": 0.8457564576,
        "n_users_evaluated": 271
      },
      {
        "model": "Hybrid",
        "k": 5,
        "precision": 0.0095940959,
        "recall": 0.0082190257,
        "ndcg": 0.0099398619,
        "coverage": 0.526,
        "diversity": 0.6538745387,
        "n_users_evaluated": 271
      },
      {
        "model": "Baseline",
        "k": 10,
        "precision": 0.0140221402,
        "recall": 0.0227437794,
        "ndcg": 0.0165610347,
        "coverage": 0.02,
        "diversity": 0.8888888889,
        "n_users_evaluated": 271
      },
      {
        "model": "Popularity",
        "k": 10,
        "precision": 0.0151291513,
        "recall": 0.0269211109,
        "ndcg": 0.0212185718,
        "coverage": 0.02,
        "diversity": 0.8888888889,
        "n_users_evaluated": 271
      },
      {
        "model": "ContentBased",
        "k": 10,
        "precision": 0.0143911439,
        "recall": 0.0171104828,
        "ndcg": 0.0160584672,
        "coverage": 0.842,
        "diversity": 0.0,
        "n_users_evaluated": 271
      },
      {
        "model": "Collaborative",
        "k": 10,
        "precision": 0.0162361624,
        "recall": 0.0275138863,
        "ndcg": 0.0209719899,
        "coverage": 0.574,
        "diversity": 0.8476424764,
        "n_users_evaluated": 271
      },
      {
        "model": "Hybrid",
        "k": 10,
        "precision": 0.0118081181,
        "recall": 0.0177281001,
        "ndcg": 0.0138917159,
        "coverage": 0.724,
        "diversity": 0.6964329643,
        "n_users_evaluated": 271
      },
      {
        "model": "Baseline",
        "k": 20,
        "precision": 0.0151291513,
        "recall": 0.0452910251,
        "ndcg": 0.0272629872,
        "coverage": 0.04,
        "diversity": 0.8789473684,
        "n_users_evaluated": 271
      },
      {
        "model": "Popularity",
        "k": 20,
        "precision": 0.0149446494,
        "recall": 0.0497190694,
        "ndcg": 0.0312104449,
        "coverage": 0.04,
        "diversity": 0.8684210526,
        "n_users_evaluated": 271
      },
      {
        "model": "ContentBased",
        "k": 20,
        "precision": 0.0147601476,
        "recall": 0.0353546566,
        "ndcg": 0.0250467169,
        "coverage": 0.93,
        "diversity": 0.0180811808,
        "n_users_evaluated": 271
      },
      {
        "model": "Collaborative",
        "k": 20,
        "precision": 0.0167896679,
        "recall": 0.0556915,
        "ndcg": 0.033014776,
        "coverage": 0.694,
        "diversity": 0.8510196155,
        "n_users_evaluated": 271
      },
      {
        "model": "Hybrid",
        "k": 20,
        "precision": 0.0123616236,
        "recall": 0.0352719236,
        "ndcg": 0.0219310502,
        "coverage": 0.872,
        "diversity": 0.7203728879,
        "n_users_evaluated": 271
      }
    ]
  },
  "eval_80_20": {
    "source_file": "results/eval_80_20.csv",
    "rows": [
      {
        "protocol": "80/20 split",
        "cutoff": "2025-02-23",
        "model": "Baseline",
        "k": 10,
        "precision": 0.0099236641,
        "recall": 0.0266601401,
        "ndcg": 0.0169975826,
        "coverage": 0.02,
        "diversity": 0.7777777778,
        "n_users_evaluated": 262
      },
      {
        "protocol": "80/20 split",
        "cutoff": "2025-02-23",
        "model": "Popularity",
        "k": 10,
        "precision": 0.0118320611,
        "recall": 0.0320959045,
        "ndcg": 0.0215246192,
        "coverage": 0.02,
        "diversity": 0.8888888889,
        "n_users_evaluated": 262
      },
      {
        "protocol": "80/20 split",
        "cutoff": "2025-02-23",
        "model": "ContentBased",
        "k": 10,
        "precision": 0.008778626,
        "recall": 0.014897613,
        "ndcg": 0.0123534775,
        "coverage": 0.846,
        "diversity": 0.0,
        "n_users_evaluated": 262
      },
      {
        "protocol": "80/20 split",
        "cutoff": "2025-02-23",
        "model": "Collaborative",
        "k": 10,
        "precision": 0.0125954198,
        "recall": 0.0322034412,
        "ndcg": 0.0199878365,
        "coverage": 0.58,
        "diversity": 0.8567430025,
        "n_users_evaluated": 262
      },
      {
        "protocol": "80/20 split",
        "cutoff": "2025-02-23",
        "model": "Hybrid",
        "k": 10,
        "precision": 0.008778626,
        "recall": 0.0201670467,
        "ndcg": 0.013610623,
        "coverage": 0.722,
        "diversity": 0.6854113656,
        "n_users_evaluated": 262
      },
      {
        "protocol": "Fixed-date (2025-01-01)",
        "cutoff": "2025-01-01",
        "model": "Baseline",
        "k": 10,
        "precision": 0.0140221402,
        "recall": 0.0227437794,
        "ndcg": 0.0165610347,
        "coverage": 0.02,
        "diversity": 0.8888888889,
        "n_users_evaluated": 271
      },
      {
        "protocol": "Fixed-date (2025-01-01)",
        "cutoff": "2025-01-01",
        "model": "Popularity",
        "k": 10,
        "precision": 0.0151291513,
        "recall": 0.0269211109,
        "ndcg": 0.0212185718,
        "coverage": 0.02,
        "diversity": 0.8888888889,
        "n_users_evaluated": 271
      },
      {
        "protocol": "Fixed-date (2025-01-01)",
        "cutoff": "2025-01-01",
        "model": "ContentBased",
        "k": 10,
        "precision": 0.0143911439,
        "recall": 0.0171104828,
        "ndcg": 0.0160584672,
        "coverage": 0.842,
        "diversity": 0.0,
        "n_users_evaluated": 271
      },
      {
        "protocol": "Fixed-date (2025-01-01)",
        "cutoff": "2025-01-01",
        "model": "Collaborative",
        "k": 10,
        "precision": 0.0162361624,
        "recall": 0.0275138863,
        "ndcg": 0.0209719899,
        "coverage": 0.574,
        "diversity": 0.8476424764,
        "n_users_evaluated": 271
      },
      {
        "protocol": "Fixed-date (2025-01-01)",
        "cutoff": "2025-01-01",
        "model": "Hybrid",
        "k": 10,
        "precision": 0.0118081181,
        "recall": 0.0177281001,
        "ndcg": 0.0138917159,
        "coverage": 0.724,
        "diversity": 0.6964329643,
        "n_users_evaluated": 271
      }
    ]
  },
  "significance": {
    "source_file": "results/significance_tests.csv",
    "rows": [
      {
        "comparison": "Hybrid vs Baseline",
        "metric": "Precision@10",
        "mean_hybrid": 0.008778626,
        "mean_other": 0.0099236641,
        "mean_diff": -0.0011450382,
        "t_stat": -0.4568042916,
        "p_ttest": 0.6481916623,
        "w_stat": 380.0,
        "p_wilcoxon": 0.6473147844,
        "ci95_low": -0.0057251908,
        "ci95_high": 0.0034351145
      },
      {
        "comparison": "Hybrid vs Baseline",
        "metric": "NDCG@10",
        "mean_hybrid": 0.013610623,
        "mean_other": 0.0169975826,
        "mean_diff": -0.0033869596,
        "t_stat": -0.7088520189,
        "p_ttest": 0.4790489752,
        "w_stat": 411.0,
        "p_wilcoxon": 0.4540329444,
        "ci95_low": -0.0122987919,
        "ci95_high": 0.0058843241
      },
      {
        "comparison": "Hybrid vs ContentBased",
        "metric": "Precision@10",
        "mean_hybrid": 0.008778626,
        "mean_other": 0.008778626,
        "mean_diff": 2.11874623e-19,
        "t_stat": 8.760317498e-17,
        "p_ttest": 1.0,
        "w_stat": 351.5,
        "p_wilcoxon": 1.0,
        "ci95_low": -0.0045801527,
        "ci95_high": 0.0045801527
      },
      {
        "comparison": "Hybrid vs ContentBased",
        "metric": "NDCG@10",
        "mean_hybrid": 0.013610623,
        "mean_other": 0.0123534775,
        "mean_diff": 0.0012571455,
        "t_stat": 0.3011207328,
        "p_ttest": 0.7635621834,
        "w_stat": 394.5,
        "p_wilcoxon": 0.6408149405,
        "ci95_low": -0.0069358577,
        "ci95_high": 0.0094071956
      },
      {
        "comparison": "Hybrid vs Collaborative",
        "metric": "Precision@10",
        "mean_hybrid": 0.008778626,
        "mean_other": 0.0125954198,
        "mean_diff": -0.0038167939,
        "t_stat": -2.2534020972,
        "p_ttest": 0.0250641604,
        "w_stat": 52.5,
        "p_wilcoxon": 0.0253473187,
        "ci95_low": -0.0072519084,
        "ci95_high": -0.0007633588
      },
      {
        "comparison": "Hybrid vs Collaborative",
        "metric": "NDCG@10",
        "mean_hybrid": 0.013610623,
        "mean_other": 0.0199878365,
        "mean_diff": -0.0063772135,
        "t_stat": -2.6107364206,
        "p_ttest": 0.0095572253,
        "w_stat": 138.5,
        "p_wilcoxon": 0.0111700648,
        "ci95_low": -0.0114905604,
        "ci95_high": -0.0017623021
      }
    ]
  },
  "alpha_strategy": {
    "source_file": "results/alpha_strategy_ablation.csv",
    "rows": [
      {
        "family": "fixed",
        "config": "fixed alpha=0.00",
        "strategy": "fixed",
        "alpha": 0.0,
        "gamma": 3,
        "freshness_boost": true,
        "festival_boost": true,
        "k": 10,
        "precision": 0.0132841328,
        "recall": 0.0158043269,
        "ndcg": 0.0137178616,
        "coverage": 0.832,
        "n_users_evaluated": 271
      },
      {
        "family": "fixed",
        "config": "fixed alpha=0.25",
        "strategy": "fixed",
        "alpha": 0.25,
        "gamma": 3,
        "freshness_boost": true,
        "festival_boost": true,
        "k": 10,
        "precision": 0.0129151292,
        "recall": 0.0181149928,
        "ndcg": 0.0162047091,
        "coverage": 0.896,
        "n_users_evaluated": 271
      },
      {
        "family": "fixed",
        "config": "fixed alpha=0.50",
        "strategy": "fixed",
        "alpha": 0.5,
        "gamma": 3,
        "freshness_boost": true,
        "festival_boost": true,
        "k": 10,
        "precision": 0.0140221402,
        "recall": 0.0192949936,
        "ndcg": 0.0177517172,
        "coverage": 0.912,
        "n_users_evaluated": 271
      },
      {
        "family": "fixed",
        "config": "fixed alpha=0.75",
        "strategy": "fixed",
        "alpha": 0.75,
        "gamma": 3,
        "freshness_boost": true,
        "festival_boost": true,
        "k": 10,
        "precision": 0.0140221402,
        "recall": 0.0219818926,
        "ndcg": 0.017438645,
        "coverage": 0.844,
        "n_users_evaluated": 271
      },
      {
        "family": "fixed",
        "config": "fixed alpha=1.00",
        "strategy": "fixed",
        "alpha": 1.0,
        "gamma": 3,
        "freshness_boost": true,
        "festival_boost": true,
        "k": 10,
        "precision": 0.0143911439,
        "recall": 0.0252954712,
        "ndcg": 0.0196305757,
        "coverage": 0.554,
        "n_users_evaluated": 271
      },
      {
        "family": "adaptive",
        "config": "adaptive gamma=1",
        "strategy": "adaptive",
        "alpha": null,
        "gamma": 1,
        "freshness_boost": true,
        "festival_boost": true,
        "k": 10,
        "precision": 0.0118081181,
        "recall": 0.0181980074,
        "ndcg": 0.0156194224,
        "coverage": 0.672,
        "n_users_evaluated": 271
      },
      {
        "family": "adaptive",
        "config": "adaptive gamma=3",
        "strategy": "adaptive",
        "alpha": null,
        "gamma": 3,
        "freshness_boost": true,
        "festival_boost": true,
        "k": 10,
        "precision": 0.0118081181,
        "recall": 0.0177281001,
        "ndcg": 0.0138917159,
        "coverage": 0.724,
        "n_users_evaluated": 271
      },
      {
        "family": "adaptive",
        "config": "adaptive gamma=5",
        "strategy": "adaptive",
        "alpha": null,
        "gamma": 5,
        "freshness_boost": true,
        "festival_boost": true,
        "k": 10,
        "precision": 0.0103321033,
        "recall": 0.0147511775,
        "ndcg": 0.0128317719,
        "coverage": 0.808,
        "n_users_evaluated": 271
      },
      {
        "family": "adaptive",
        "config": "adaptive gamma=10",
        "strategy": "adaptive",
        "alpha": null,
        "gamma": 10,
        "freshness_boost": true,
        "festival_boost": true,
        "k": 10,
        "precision": 0.0114391144,
        "recall": 0.015035477,
        "ndcg": 0.0126008253,
        "coverage": 0.896,
        "n_users_evaluated": 271
      },
      {
        "family": "switching",
        "config": "switching gamma=1",
        "strategy": "switching",
        "alpha": null,
        "gamma": 1,
        "freshness_boost": true,
        "festival_boost": true,
        "k": 10,
        "precision": 0.0136531365,
        "recall": 0.0222204405,
        "ndcg": 0.0182078159,
        "coverage": 0.552,
        "n_users_evaluated": 271
      },
      {
        "family": "switching",
        "config": "switching gamma=3",
        "strategy": "switching",
        "alpha": null,
        "gamma": 3,
        "freshness_boost": true,
        "festival_boost": true,
        "k": 10,
        "precision": 0.0136531365,
        "recall": 0.0222204405,
        "ndcg": 0.0182078159,
        "coverage": 0.608,
        "n_users_evaluated": 271
      },
      {
        "family": "switching",
        "config": "switching gamma=5",
        "strategy": "switching",
        "alpha": null,
        "gamma": 5,
        "freshness_boost": true,
        "festival_boost": true,
        "k": 10,
        "precision": 0.0136531365,
        "recall": 0.0222204405,
        "ndcg": 0.0182078159,
        "coverage": 0.608,
        "n_users_evaluated": 271
      },
      {
        "family": "boost",
        "config": "adaptive gamma=3 boosts:both-on",
        "strategy": "adaptive",
        "alpha": null,
        "gamma": 3,
        "freshness_boost": true,
        "festival_boost": true,
        "k": 10,
        "precision": 0.0118081181,
        "recall": 0.0177281001,
        "ndcg": 0.0138917159,
        "coverage": 0.724,
        "n_users_evaluated": 271
      },
      {
        "family": "boost",
        "config": "adaptive gamma=3 boosts:freshness-off",
        "strategy": "adaptive",
        "alpha": null,
        "gamma": 3,
        "freshness_boost": false,
        "festival_boost": true,
        "k": 10,
        "precision": 0.0129151292,
        "recall": 0.0192348652,
        "ndcg": 0.0161293391,
        "coverage": 0.732,
        "n_users_evaluated": 271
      },
      {
        "family": "boost",
        "config": "adaptive gamma=3 boosts:festival-off",
        "strategy": "adaptive",
        "alpha": null,
        "gamma": 3,
        "freshness_boost": true,
        "festival_boost": false,
        "k": 10,
        "precision": 0.0118081181,
        "recall": 0.0177281001,
        "ndcg": 0.0138917159,
        "coverage": 0.724,
        "n_users_evaluated": 271
      },
      {
        "family": "boost",
        "config": "adaptive gamma=3 boosts:both-off",
        "strategy": "adaptive",
        "alpha": null,
        "gamma": 3,
        "freshness_boost": false,
        "festival_boost": false,
        "k": 10,
        "precision": 0.0129151292,
        "recall": 0.0192348652,
        "ndcg": 0.0161293391,
        "coverage": 0.732,
        "n_users_evaluated": 271
      }
    ]
  },
  "gamma_ablation": {
    "source_file": "results/gamma_ablation.csv",
    "rows": [
      {
        "gamma": 1,
        "k": 10,
        "precision": 0.0118081181,
        "recall": 0.0181980074,
        "ndcg": 0.0156194224,
        "coverage": 0.672
      },
      {
        "gamma": 3,
        "k": 10,
        "precision": 0.0118081181,
        "recall": 0.0177281001,
        "ndcg": 0.0138917159,
        "coverage": 0.724
      },
      {
        "gamma": 5,
        "k": 10,
        "precision": 0.0103321033,
        "recall": 0.0147511775,
        "ndcg": 0.0128317719,
        "coverage": 0.808
      },
      {
        "gamma": 10,
        "k": 10,
        "precision": 0.0114391144,
        "recall": 0.015035477,
        "ndcg": 0.0126008253,
        "coverage": 0.896
      }
    ]
  },
  "cold_items": {
    "source_file": "results/cold_items.csv",
    "rows": [
      {
        "model": "Hybrid",
        "freshness_boost": true,
        "cold_item_coverage": 0.925,
        "mean_cold_items_per_list": 1.6642066421
      },
      {
        "model": "Hybrid",
        "freshness_boost": false,
        "cold_item_coverage": 0.925,
        "mean_cold_items_per_list": 1.0
      },
      {
        "model": "Baseline",
        "freshness_boost": null,
        "cold_item_coverage": 0.0,
        "mean_cold_items_per_list": 0.0
      },
      {
        "model": "Popularity",
        "freshness_boost": null,
        "cold_item_coverage": 0.0,
        "mean_cold_items_per_list": 0.0
      }
    ]
  },
  "latency": {
    "source_file": "results/latency_live.csv",
    "rows": [
      {
        "scenario": "cache_miss_full_inference",
        "mean_latency_ms": 186.3222,
        "p95_latency_ms": 237.8873,
        "n_requests": 200,
        "measurement": "live"
      },
      {
        "scenario": "cache_hit_live_redis",
        "mean_latency_ms": 1.9043,
        "p95_latency_ms": 2.6833,
        "n_requests": 200,
        "measurement": "live"
      }
    ]
  },
  "ui": {
    "hybrid_vs_baseline": [
      {
        "k": 5,
        "rows": [
          {
            "metric": "Precision",
            "hybrid": 0.0095940959,
            "baseline": 0.0132841328
          },
          {
            "metric": "Recall",
            "hybrid": 0.0082190257,
            "baseline": 0.0094521919
          },
          {
            "metric": "NDCG",
            "hybrid": 0.0099398619,
            "baseline": 0.0115235318
          },
          {
            "metric": "Coverage",
            "hybrid": 0.526,
            "baseline": 0.01
          },
          {
            "metric": "Diversity",
            "hybrid": 0.6538745387,
            "baseline": 0.9
          }
        ]
      },
      {
        "k": 10,
        "rows": [
          {
            "metric": "Precision",
            "hybrid": 0.0118081181,
            "baseline": 0.0140221402
          },
          {
            "metric": "Recall",
            "hybrid": 0.0177281001,
            "baseline": 0.0227437794
          },
          {
            "metric": "NDCG",
            "hybrid": 0.0138917159,
            "baseline": 0.0165610347
          },
          {
            "metric": "Coverage",
            "hybrid": 0.724,
            "baseline": 0.02
          },
          {
            "metric": "Diversity",
            "hybrid": 0.6964329643,
            "baseline": 0.8888888889
          }
        ]
      },
      {
        "k": 20,
        "rows": [
          {
            "metric": "Precision",
            "hybrid": 0.0123616236,
            "baseline": 0.0151291513
          },
          {
            "metric": "Recall",
            "hybrid": 0.0352719236,
            "baseline": 0.0452910251
          },
          {
            "metric": "NDCG",
            "hybrid": 0.0219310502,
            "baseline": 0.0272629872
          },
          {
            "metric": "Coverage",
            "hybrid": 0.872,
            "baseline": 0.04
          },
          {
            "metric": "Diversity",
            "hybrid": 0.7203728879,
            "baseline": 0.8789473684
          }
        ]
      }
    ],
    "headline": {
      "n_users": 271,
      "protocol": "Leak-free time split (train < 2025-01-01, test >= 2025-01-01)",
      "coverage_at_10": {
        "hybrid": 0.724,
        "baseline": 0.02
      },
      "precision_at_10": {
        "hybrid": 0.0118081181,
        "baseline": 0.0140221402
      },
      "ndcg_at_10": {
        "hybrid": 0.0138917159,
        "baseline": 0.0165610347
      },
      "cold_item_coverage": {
        "hybrid": 0.925,
        "baseline": 0.0
      },
      "accuracy_significance": {
        "comparison": "Hybrid vs Baseline",
        "metric": "Precision@10",
        "p_ttest": 0.6481916623,
        "verdict": "not statistically significant"
      },
      "latency_ms": {
        "cache_miss_mean": 186.3222,
        "cache_hit_mean": 1.9043,
        "measurement": "live Redis"
      }
    }
  }
} as const;

export const HYBRID_VS_BASELINE = THESIS_METRICS.ui.hybrid_vs_baseline;
export const HEADLINE = THESIS_METRICS.ui.headline;
