// AUTO-GENERATED by hybrid-model/backend/scripts/export_metrics.py.
// DO NOT EDIT BY HAND. Run `poetry run python scripts/export_metrics.py`
// (from hybrid-model/backend) to regenerate from results/.
// Every number here is traceable to the source_file named in its section.

export const THESIS_METRICS = {
  "_meta": {
    "generated_by": "scripts/export_metrics.py",
    "dataset_version": "v4",
    "note": "AUTO-GENERATED. Do not edit by hand. Every number is traceable to the source_file named in its section."
  },
  "clean_eval": {
    "source_file": "results/clean_eval_results.csv",
    "rows": [
      {
        "model": "Baseline",
        "k": 5,
        "precision": 0.0067274001,
        "recall": 0.0035284703,
        "ndcg": 0.0072824969,
        "coverage": 0.002,
        "diversity": 1.0,
        "n_users_evaluated": 1427
      },
      {
        "model": "Baseline",
        "k": 10,
        "precision": 0.0060967064,
        "recall": 0.0060365532,
        "ndcg": 0.0071451521,
        "coverage": 0.004,
        "diversity": 0.8666666667,
        "n_users_evaluated": 1427
      },
      {
        "model": "Baseline",
        "k": 20,
        "precision": 0.0065522074,
        "recall": 0.0129742747,
        "ndcg": 0.0097950326,
        "coverage": 0.008,
        "diversity": 0.8684210526,
        "n_users_evaluated": 1427
      },
      {
        "model": "Hybrid",
        "k": 5,
        "precision": 0.0085494043,
        "recall": 0.0036125125,
        "ndcg": 0.0109562665,
        "coverage": 0.2032,
        "diversity": 0.4649614576,
        "n_users_evaluated": 1427
      },
      {
        "model": "Hybrid",
        "k": 10,
        "precision": 0.0067274001,
        "recall": 0.0061154051,
        "ndcg": 0.0091621596,
        "coverage": 0.2408,
        "diversity": 0.402771938,
        "n_users_evaluated": 1427
      },
      {
        "model": "Hybrid",
        "k": 20,
        "precision": 0.0069726699,
        "recall": 0.0152483344,
        "ndcg": 0.0119429454,
        "coverage": 0.4428,
        "diversity": 0.4439899679,
        "n_users_evaluated": 1427
      }
    ]
  },
  "components_eval": {
    "source_file": "results/components_eval.csv",
    "rows": [
      {
        "model": "Baseline",
        "k": 5,
        "precision": 0.0067274001,
        "recall": 0.0035284703,
        "ndcg": 0.0072824969,
        "coverage": 0.002,
        "diversity": 1.0,
        "n_users_evaluated": 1427
      },
      {
        "model": "Popularity",
        "k": 5,
        "precision": 0.0109320252,
        "recall": 0.0047633624,
        "ndcg": 0.0103211061,
        "coverage": 0.002,
        "diversity": 0.4,
        "n_users_evaluated": 1427
      },
      {
        "model": "ContentBased",
        "k": 5,
        "precision": 0.0113524877,
        "recall": 0.0047694093,
        "ndcg": 0.011785058,
        "coverage": 0.3872,
        "diversity": 0.0,
        "n_users_evaluated": 1427
      },
      {
        "model": "Collaborative",
        "k": 5,
        "precision": 0.0159775753,
        "recall": 0.0062368728,
        "ndcg": 0.0169935138,
        "coverage": 0.1032,
        "diversity": 0.7398037842,
        "n_users_evaluated": 1427
      },
      {
        "model": "Hybrid",
        "k": 5,
        "precision": 0.0085494043,
        "recall": 0.0036125125,
        "ndcg": 0.0109562665,
        "coverage": 0.2032,
        "diversity": 0.4649614576,
        "n_users_evaluated": 1427
      },
      {
        "model": "Baseline",
        "k": 10,
        "precision": 0.0060967064,
        "recall": 0.0060365532,
        "ndcg": 0.0071451521,
        "coverage": 0.004,
        "diversity": 0.8666666667,
        "n_users_evaluated": 1427
      },
      {
        "model": "Popularity",
        "k": 10,
        "precision": 0.0112123336,
        "recall": 0.0111906494,
        "ndcg": 0.0115428843,
        "coverage": 0.004,
        "diversity": 0.6888888889,
        "n_users_evaluated": 1427
      },
      {
        "model": "ContentBased",
        "k": 10,
        "precision": 0.0117028732,
        "recall": 0.0095600795,
        "ndcg": 0.0121109245,
        "coverage": 0.6928,
        "diversity": 0.0,
        "n_users_evaluated": 1427
      },
      {
        "model": "Collaborative",
        "k": 10,
        "precision": 0.0142256482,
        "recall": 0.0112230557,
        "ndcg": 0.0155734939,
        "coverage": 0.162,
        "diversity": 0.7700225804,
        "n_users_evaluated": 1427
      },
      {
        "model": "Hybrid",
        "k": 10,
        "precision": 0.0067274001,
        "recall": 0.0061154051,
        "ndcg": 0.0091621596,
        "coverage": 0.2408,
        "diversity": 0.402771938,
        "n_users_evaluated": 1427
      },
      {
        "model": "Baseline",
        "k": 20,
        "precision": 0.0065522074,
        "recall": 0.0129742747,
        "ndcg": 0.0097950326,
        "coverage": 0.008,
        "diversity": 0.8684210526,
        "n_users_evaluated": 1427
      },
      {
        "model": "Popularity",
        "k": 20,
        "precision": 0.0116327961,
        "recall": 0.021841355,
        "ndcg": 0.0160177332,
        "coverage": 0.008,
        "diversity": 0.7894736842,
        "n_users_evaluated": 1427
      },
      {
        "model": "ContentBased",
        "k": 20,
        "precision": 0.0121583742,
        "recall": 0.0198858658,
        "ndcg": 0.0163583066,
        "coverage": 0.9064,
        "diversity": 0.0,
        "n_users_evaluated": 1427
      },
      {
        "model": "Collaborative",
        "k": 20,
        "precision": 0.0121583742,
        "recall": 0.0215477113,
        "ndcg": 0.0185107691,
        "coverage": 0.2496,
        "diversity": 0.7913141298,
        "n_users_evaluated": 1427
      },
      {
        "model": "Hybrid",
        "k": 20,
        "precision": 0.0069726699,
        "recall": 0.0152483344,
        "ndcg": 0.0119429454,
        "coverage": 0.4428,
        "diversity": 0.4439899679,
        "n_users_evaluated": 1427
      }
    ]
  },
  "eval_80_20": {
    "source_file": "results/eval_80_20.csv",
    "rows": [
      {
        "protocol": "80/20 split",
        "cutoff": "2025-07-30",
        "model": "Baseline",
        "k": 10,
        "precision": 0.003277439,
        "recall": 0.0070947663,
        "ndcg": 0.0053036577,
        "coverage": 0.004,
        "diversity": 0.8444444444,
        "n_users_evaluated": 1312
      },
      {
        "protocol": "80/20 split",
        "cutoff": "2025-07-30",
        "model": "Popularity",
        "k": 10,
        "precision": 0.0040396341,
        "recall": 0.0076606934,
        "ndcg": 0.0068041408,
        "coverage": 0.004,
        "diversity": 0.8666666667,
        "n_users_evaluated": 1312
      },
      {
        "protocol": "80/20 split",
        "cutoff": "2025-07-30",
        "model": "ContentBased",
        "k": 10,
        "precision": 0.0066310976,
        "recall": 0.0132761357,
        "ndcg": 0.0104772802,
        "coverage": 0.6964,
        "diversity": 0.0,
        "n_users_evaluated": 1312
      },
      {
        "protocol": "80/20 split",
        "cutoff": "2025-07-30",
        "model": "Collaborative",
        "k": 10,
        "precision": 0.0067073171,
        "recall": 0.0132549361,
        "ndcg": 0.0110453626,
        "coverage": 0.1572,
        "diversity": 0.7642107046,
        "n_users_evaluated": 1312
      },
      {
        "protocol": "80/20 split",
        "cutoff": "2025-07-30",
        "model": "Hybrid",
        "k": 10,
        "precision": 0.0035060976,
        "recall": 0.0070899269,
        "ndcg": 0.0069437981,
        "coverage": 0.2452,
        "diversity": 0.4479844173,
        "n_users_evaluated": 1312
      },
      {
        "protocol": "Fixed-date (2025-01-01)",
        "cutoff": "2025-01-01",
        "model": "Baseline",
        "k": 10,
        "precision": 0.0060967064,
        "recall": 0.0060365532,
        "ndcg": 0.0071451521,
        "coverage": 0.004,
        "diversity": 0.8666666667,
        "n_users_evaluated": 1427
      },
      {
        "protocol": "Fixed-date (2025-01-01)",
        "cutoff": "2025-01-01",
        "model": "Popularity",
        "k": 10,
        "precision": 0.0112123336,
        "recall": 0.0111906494,
        "ndcg": 0.0115428843,
        "coverage": 0.004,
        "diversity": 0.6888888889,
        "n_users_evaluated": 1427
      },
      {
        "protocol": "Fixed-date (2025-01-01)",
        "cutoff": "2025-01-01",
        "model": "ContentBased",
        "k": 10,
        "precision": 0.0117028732,
        "recall": 0.0095600795,
        "ndcg": 0.0121109245,
        "coverage": 0.6928,
        "diversity": 0.0,
        "n_users_evaluated": 1427
      },
      {
        "protocol": "Fixed-date (2025-01-01)",
        "cutoff": "2025-01-01",
        "model": "Collaborative",
        "k": 10,
        "precision": 0.0142256482,
        "recall": 0.0112230557,
        "ndcg": 0.0155734939,
        "coverage": 0.162,
        "diversity": 0.7700225804,
        "n_users_evaluated": 1427
      },
      {
        "protocol": "Fixed-date (2025-01-01)",
        "cutoff": "2025-01-01",
        "model": "Hybrid",
        "k": 10,
        "precision": 0.0067274001,
        "recall": 0.0061154051,
        "ndcg": 0.0091621596,
        "coverage": 0.2408,
        "diversity": 0.402771938,
        "n_users_evaluated": 1427
      }
    ]
  },
  "significance": {
    "source_file": "results/significance_tests.csv",
    "rows": [
      {
        "comparison": "Hybrid vs Baseline",
        "metric": "Precision@10",
        "mean_hybrid": 0.0035060976,
        "mean_other": 0.003277439,
        "mean_diff": 0.0002286585,
        "t_stat": 0.3215238392,
        "p_ttest": 0.7478647027,
        "w_stat": 1848.0,
        "p_wilcoxon": 0.7477301646,
        "ci95_low": -0.0011432927,
        "ci95_high": 0.0015243902
      },
      {
        "comparison": "Hybrid vs Baseline",
        "metric": "NDCG@10",
        "mean_hybrid": 0.0069437981,
        "mean_other": 0.0053036577,
        "mean_diff": 0.0016401404,
        "t_stat": 1.1178733007,
        "p_ttest": 0.2638259139,
        "w_stat": 1645.5,
        "p_wilcoxon": 0.1934712577,
        "ci95_low": -0.0013594638,
        "ci95_high": 0.0045646118
      },
      {
        "comparison": "Hybrid vs ContentBased",
        "metric": "Precision@10",
        "mean_hybrid": 0.0035060976,
        "mean_other": 0.0066310976,
        "mean_diff": -0.003125,
        "t_stat": -3.518020449,
        "p_ttest": 0.0004496411,
        "w_stat": 2684.0,
        "p_wilcoxon": 0.0004545399,
        "ci95_low": -0.0049542683,
        "ci95_high": -0.0012957317
      },
      {
        "comparison": "Hybrid vs ContentBased",
        "metric": "NDCG@10",
        "mean_hybrid": 0.0069437981,
        "mean_other": 0.0104772802,
        "mean_diff": -0.0035334821,
        "t_stat": -2.0353108975,
        "p_ttest": 0.042020388,
        "w_stat": 3201.0,
        "p_wilcoxon": 0.0515692223,
        "ci95_low": -0.0068484714,
        "ci95_high": -3.74879e-05
      },
      {
        "comparison": "Hybrid vs Collaborative",
        "metric": "Precision@10",
        "mean_hybrid": 0.0035060976,
        "mean_other": 0.0067073171,
        "mean_diff": -0.0032012195,
        "t_stat": -6.2826996705,
        "p_ttest": 5e-10,
        "w_stat": 47.0,
        "p_wilcoxon": 6e-10,
        "ci95_low": -0.0042682927,
        "ci95_high": -0.0022865854
      },
      {
        "comparison": "Hybrid vs Collaborative",
        "metric": "NDCG@10",
        "mean_hybrid": 0.0069437981,
        "mean_other": 0.0110453626,
        "mean_diff": -0.0041015645,
        "t_stat": -4.9950042863,
        "p_ttest": 6.677e-07,
        "w_stat": 276.5,
        "p_wilcoxon": 4.29e-08,
        "ci95_low": -0.0057242928,
        "ci95_high": -0.0025499482
      }
    ]
  },
  "alpha_strategy": {
    "source_file": "results/alpha_strategy_ablation.csv",
    "rows": [
      {
        "family": "fixed",
        "config": "fixed alpha=0.00",
        "strategy": "fixed",
        "alpha": 0.0,
        "gamma": 3,
        "freshness_boost": true,
        "festival_boost": true,
        "k": 10,
        "precision": 0.0105115627,
        "recall": 0.0085903425,
        "ndcg": 0.0090876595,
        "coverage": 0.6924,
        "n_users_evaluated": 1427
      },
      {
        "family": "fixed",
        "config": "fixed alpha=0.25",
        "strategy": "fixed",
        "alpha": 0.25,
        "gamma": 3,
        "freshness_boost": true,
        "festival_boost": true,
        "k": 10,
        "precision": 0.0100210231,
        "recall": 0.0081308831,
        "ndcg": 0.0098703199,
        "coverage": 0.8928,
        "n_users_evaluated": 1427
      },
      {
        "family": "fixed",
        "config": "fixed alpha=0.50",
        "strategy": "fixed",
        "alpha": 0.5,
        "gamma": 3,
        "freshness_boost": true,
        "festival_boost": true,
        "k": 10,
        "precision": 0.0095304835,
        "recall": 0.0076752389,
        "ndcg": 0.0095323008,
        "coverage": 0.8288,
        "n_users_evaluated": 1427
      },
      {
        "family": "fixed",
        "config": "fixed alpha=0.75",
        "strategy": "fixed",
        "alpha": 0.75,
        "gamma": 3,
        "freshness_boost": true,
        "festival_boost": true,
        "k": 10,
        "precision": 0.0096706377,
        "recall": 0.007837385,
        "ndcg": 0.0123351943,
        "coverage": 0.4568,
        "n_users_evaluated": 1427
      },
      {
        "family": "fixed",
        "config": "fixed alpha=1.00",
        "strategy": "fixed",
        "alpha": 1.0,
        "gamma": 3,
        "freshness_boost": true,
        "festival_boost": true,
        "k": 10,
        "precision": 0.0141555711,
        "recall": 0.0112463758,
        "ndcg": 0.0154948061,
        "coverage": 0.1544,
        "n_users_evaluated": 1427
      },
      {
        "family": "adaptive",
        "config": "adaptive gamma=1",
        "strategy": "adaptive",
        "alpha": null,
        "gamma": 1,
        "freshness_boost": true,
        "festival_boost": true,
        "k": 10,
        "precision": 0.0064470918,
        "recall": 0.0050642488,
        "ndcg": 0.008670627,
        "coverage": 0.2376,
        "n_users_evaluated": 1427
      },
      {
        "family": "adaptive",
        "config": "adaptive gamma=3",
        "strategy": "adaptive",
        "alpha": null,
        "gamma": 3,
        "freshness_boost": true,
        "festival_boost": true,
        "k": 10,
        "precision": 0.0046250876,
        "recall": 0.0034990559,
        "ndcg": 0.0055689837,
        "coverage": 0.2872,
        "n_users_evaluated": 1427
      },
      {
        "family": "adaptive",
        "config": "adaptive gamma=5",
        "strategy": "adaptive",
        "alpha": null,
        "gamma": 5,
        "freshness_boost": true,
        "festival_boost": true,
        "k": 10,
        "precision": 0.0037841626,
        "recall": 0.0028949341,
        "ndcg": 0.004069159,
        "coverage": 0.372,
        "n_users_evaluated": 1427
      },
      {
        "family": "adaptive",
        "config": "adaptive gamma=10",
        "strategy": "adaptive",
        "alpha": null,
        "gamma": 10,
        "freshness_boost": true,
        "festival_boost": true,
        "k": 10,
        "precision": 0.0034337772,
        "recall": 0.0027705756,
        "ndcg": 0.0032899641,
        "coverage": 0.5684,
        "n_users_evaluated": 1427
      },
      {
        "family": "switching",
        "config": "switching gamma=1",
        "strategy": "switching",
        "alpha": null,
        "gamma": 1,
        "freshness_boost": true,
        "festival_boost": true,
        "k": 10,
        "precision": 0.0141555711,
        "recall": 0.0112463758,
        "ndcg": 0.0154948061,
        "coverage": 0.1536,
        "n_users_evaluated": 1427
      },
      {
        "family": "switching",
        "config": "switching gamma=3",
        "strategy": "switching",
        "alpha": null,
        "gamma": 3,
        "freshness_boost": true,
        "festival_boost": true,
        "k": 10,
        "precision": 0.0141555711,
        "recall": 0.0112463758,
        "ndcg": 0.0154948061,
        "coverage": 0.3644,
        "n_users_evaluated": 1427
      },
      {
        "family": "switching",
        "config": "switching gamma=5",
        "strategy": "switching",
        "alpha": null,
        "gamma": 5,
        "freshness_boost": true,
        "festival_boost": true,
        "k": 10,
        "precision": 0.0141555711,
        "recall": 0.0112463758,
        "ndcg": 0.0154948061,
        "coverage": 0.368,
        "n_users_evaluated": 1427
      },
      {
        "family": "boost",
        "config": "adaptive gamma=3 boosts:both-on",
        "strategy": "adaptive",
        "alpha": null,
        "gamma": 3,
        "freshness_boost": true,
        "festival_boost": true,
        "k": 10,
        "precision": 0.0046250876,
        "recall": 0.0034990559,
        "ndcg": 0.0055689837,
        "coverage": 0.2872,
        "n_users_evaluated": 1427
      },
      {
        "family": "boost",
        "config": "adaptive gamma=3 boosts:freshness-off",
        "strategy": "adaptive",
        "alpha": null,
        "gamma": 3,
        "freshness_boost": false,
        "festival_boost": true,
        "k": 10,
        "precision": 0.0088297127,
        "recall": 0.0070995157,
        "ndcg": 0.0099332557,
        "coverage": 0.5096,
        "n_users_evaluated": 1427
      },
      {
        "family": "boost",
        "config": "adaptive gamma=3 boosts:festival-off",
        "strategy": "adaptive",
        "alpha": null,
        "gamma": 3,
        "freshness_boost": true,
        "festival_boost": false,
        "k": 10,
        "precision": 0.0046250876,
        "recall": 0.0034990559,
        "ndcg": 0.0055689837,
        "coverage": 0.2872,
        "n_users_evaluated": 1427
      },
      {
        "family": "boost",
        "config": "adaptive gamma=3 boosts:both-off",
        "strategy": "adaptive",
        "alpha": null,
        "gamma": 3,
        "freshness_boost": false,
        "festival_boost": false,
        "k": 10,
        "precision": 0.0088297127,
        "recall": 0.0070995157,
        "ndcg": 0.0099332557,
        "coverage": 0.5096,
        "n_users_evaluated": 1427
      }
    ]
  },
  "gamma_ablation": {
    "source_file": "results/gamma_ablation.csv",
    "rows": [
      {
        "gamma": 1,
        "k": 10,
        "precision": 0.0064470918,
        "recall": 0.0050642488,
        "ndcg": 0.008670627,
        "coverage": 0.2376
      },
      {
        "gamma": 3,
        "k": 10,
        "precision": 0.0046250876,
        "recall": 0.0034990559,
        "ndcg": 0.0055689837,
        "coverage": 0.2872
      },
      {
        "gamma": 5,
        "k": 10,
        "precision": 0.0037841626,
        "recall": 0.0028949341,
        "ndcg": 0.004069159,
        "coverage": 0.372
      },
      {
        "gamma": 10,
        "k": 10,
        "precision": 0.0034337772,
        "recall": 0.0027705756,
        "ndcg": 0.0032899641,
        "coverage": 0.5684
      }
    ]
  },
  "cold_items": {
    "source_file": "results/cold_items.csv",
    "rows": [
      {
        "model": "Hybrid",
        "freshness_boost": true,
        "cold_item_coverage": 0.895,
        "mean_cold_items_per_list": 3.0854940434
      },
      {
        "model": "Hybrid",
        "freshness_boost": false,
        "cold_item_coverage": 0.895,
        "mean_cold_items_per_list": 2.0812894184
      },
      {
        "model": "Baseline",
        "freshness_boost": null,
        "cold_item_coverage": 0.0,
        "mean_cold_items_per_list": 0.0
      },
      {
        "model": "Popularity",
        "freshness_boost": null,
        "cold_item_coverage": 0.0,
        "mean_cold_items_per_list": 0.0
      }
    ]
  },
  "latency": {
    "source_file": "results/latency_live.csv",
    "rows": [
      {
        "scenario": "cache_miss_full_inference",
        "mean_latency_ms": 9.0414,
        "p95_latency_ms": 10.0293,
        "n_requests": 200,
        "measurement": "live"
      },
      {
        "scenario": "cache_hit_live_redis",
        "mean_latency_ms": 1.4642,
        "p95_latency_ms": 1.7343,
        "n_requests": 200,
        "measurement": "live"
      }
    ]
  },
  "ui": {
    "hybrid_vs_baseline": [
      {
        "k": 5,
        "rows": [
          {
            "metric": "Precision",
            "hybrid": 0.0085494043,
            "baseline": 0.0067274001
          },
          {
            "metric": "Recall",
            "hybrid": 0.0036125125,
            "baseline": 0.0035284703
          },
          {
            "metric": "NDCG",
            "hybrid": 0.0109562665,
            "baseline": 0.0072824969
          },
          {
            "metric": "Coverage",
            "hybrid": 0.2032,
            "baseline": 0.002
          },
          {
            "metric": "Diversity",
            "hybrid": 0.4649614576,
            "baseline": 1.0
          }
        ]
      },
      {
        "k": 10,
        "rows": [
          {
            "metric": "Precision",
            "hybrid": 0.0067274001,
            "baseline": 0.0060967064
          },
          {
            "metric": "Recall",
            "hybrid": 0.0061154051,
            "baseline": 0.0060365532
          },
          {
            "metric": "NDCG",
            "hybrid": 0.0091621596,
            "baseline": 0.0071451521
          },
          {
            "metric": "Coverage",
            "hybrid": 0.2408,
            "baseline": 0.004
          },
          {
            "metric": "Diversity",
            "hybrid": 0.402771938,
            "baseline": 0.8666666667
          }
        ]
      },
      {
        "k": 20,
        "rows": [
          {
            "metric": "Precision",
            "hybrid": 0.0069726699,
            "baseline": 0.0065522074
          },
          {
            "metric": "Recall",
            "hybrid": 0.0152483344,
            "baseline": 0.0129742747
          },
          {
            "metric": "NDCG",
            "hybrid": 0.0119429454,
            "baseline": 0.0097950326
          },
          {
            "metric": "Coverage",
            "hybrid": 0.4428,
            "baseline": 0.008
          },
          {
            "metric": "Diversity",
            "hybrid": 0.4439899679,
            "baseline": 0.8684210526
          }
        ]
      }
    ],
    "headline": {
      "n_users": 1427,
      "protocol": "Leak-free time split (train < 2025-01-01, test >= 2025-01-01)",
      "coverage_at_10": {
        "hybrid": 0.2408,
        "baseline": 0.004
      },
      "precision_at_10": {
        "hybrid": 0.0067274001,
        "baseline": 0.0060967064
      },
      "ndcg_at_10": {
        "hybrid": 0.0091621596,
        "baseline": 0.0071451521
      },
      "cold_item_coverage": {
        "hybrid": 0.895,
        "baseline": 0.0
      },
      "accuracy_significance": {
        "comparison": "Hybrid vs Baseline",
        "metric": "Precision@10",
        "p_ttest": 0.7478647027,
        "verdict": "not statistically significant"
      },
      "latency_ms": {
        "cache_miss_mean": 9.0414,
        "cache_hit_mean": 1.4642,
        "measurement": "live Redis"
      }
    }
  }
} as const;

export const HYBRID_VS_BASELINE = THESIS_METRICS.ui.hybrid_vs_baseline;
export const HEADLINE = THESIS_METRICS.ui.headline;
